// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React from 'react';
import {
  PlasmicContactUsButton,
  DefaultContactUsButtonProps
} from "./plasmic/top_co_website/PlasmicContactUsButton";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ContactUsButtonProps extends Omit<DefaultContactUsButtonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultContactUsButtonProps altogether and have
// total control over the props for your component.
export interface ContactUsButtonProps extends DefaultContactUsButtonProps {
  className?: string;
}

function ContactUsButton_(
  props: ContactUsButtonProps & { ref?: React.ForwardedRef<HTMLButtonElement> }
) {
  const { ref, ...rest } = props;

  return (
    <PlasmicContactUsButton
      button6={{
        ref: ref as React.RefObject<HTMLButtonElement>
      }}
      {...rest}
    />
  );
}

export const ContactUsButton = React.forwardRef<HTMLButtonElement, ContactUsButtonProps>(
  (props, ref) => <ContactUsButton_ {...props} ref={ref} />
);

// Убедитесь, что экспорт по умолчанию соответствует
export default ContactUsButton;
