// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pnayxrZQDQNLaMhqWY9Kua

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  strapiCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof StrapiCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children } = props;

  return (
    <StrapiCredentialsProvider
      host={process.env.NEXT_PUBLIC_STRAPI_API_URL || "http://localhost:1337"}
      token={process.env.NEXT_PUBLIC_STRAPI_TOKEN}
    >
      {children}
    </StrapiCredentialsProvider>
  );
}
