// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/top_co_website/PlasmicGlobalContextsProvider";
import { useRouter } from "next/router";
import dynamicImport from 'next/dynamic';

const DynamicTopCo = dynamicImport(
  () => import('../components/DynamicTopCo'),
  { ssr: false }
);

function TopCo() {
  return <DynamicTopCo />;
}

export default TopCo;
export const dynamicConfig = "force-dynamic";