// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tVrjFA7RVCG7zyycB4xXud

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  strapiCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof StrapiCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, strapiCredentialsProviderProps } = props;

  return (
    <StrapiCredentialsProvider
      {...strapiCredentialsProviderProps}
      host={
        strapiCredentialsProviderProps &&
        "host" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.host!
          : "http://localhost:1337/api"
      }
      token={
        strapiCredentialsProviderProps &&
        "token" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.token!
          : "a83be96e7b87c4e00c2cc509fa2ebc732e0ef96b72a998726361309065f055d423e7c13dafbad002a4537e8fbdb6f90c395fb2f3f148b3c58a10c737584fc53c26ea976c7a9f93cc31a9a0e2e5114450060b65d4c4894a3e3a93646b7ab3915c617a7a72767db39b0c240ac83e3641d42971fa7ff7699bc68e8399c16e1c7956"
      }
    >
      {children}
    </StrapiCredentialsProvider>
  );
}
