// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tVrjFA7RVCG7zyycB4xXud
// Component: IHGcM1N4E6Ud

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: tVrjFA7RVCG7zyycB4xXud/projectcss
import sty from "./PlasmicBuildWithUs.module.css"; // plasmic-import: IHGcM1N4E6Ud/css

import Contact24Icon from "./icons/PlasmicIcon__Contact24"; // plasmic-import: 4_F0VNY3gp1U/icon
import Chevron24Icon from "./icons/PlasmicIcon__Chevron24"; // plasmic-import: DeKqgdmQQGn7/icon

createPlasmicElementProxy;

export type PlasmicBuildWithUs__VariantMembers = {};
export type PlasmicBuildWithUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicBuildWithUs__VariantsArgs;
export const PlasmicBuildWithUs__VariantProps = new Array<VariantPropType>();

export type PlasmicBuildWithUs__ArgsType = {};
type ArgPropType = keyof PlasmicBuildWithUs__ArgsType;
export const PlasmicBuildWithUs__ArgProps = new Array<ArgPropType>();

export type PlasmicBuildWithUs__OverridesType = {
  button?: Flex__<"div">;
  iconFrame?: Flex__<"div">;
  label?: Flex__<"div">;
};

export interface DefaultBuildWithUsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBuildWithUs__RenderFunc(props: {
  variants: PlasmicBuildWithUs__VariantsArgs;
  args: PlasmicBuildWithUs__ArgsType;
  overrides: PlasmicBuildWithUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"button"}
      data-plasmic-override={overrides.button}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.button
      )}
    >
      {false ? (
        <div
          data-plasmic-name={"iconFrame"}
          data-plasmic-override={overrides.iconFrame}
          className={classNames(projectcss.all, sty.iconFrame)}
        >
          <Contact24Icon
            className={classNames(projectcss.all, sty.svg___9EgTd)}
            role={"img"}
          />
        </div>
      ) : null}
      {(() => {
        try {
          return true;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div className={classNames(projectcss.all, sty.freeBox__kPiPp)}>
          <div className={classNames(projectcss.all, sty.freeBox__q6Bnc)}>
            <div
              data-plasmic-name={"label"}
              data-plasmic-override={overrides.label}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.label
              )}
            >
              {"Build With Us"}
            </div>
          </div>
        </div>
      ) : null}
      <div className={classNames(projectcss.all, sty.freeBox__pviOv)}>
        <Chevron24Icon
          className={classNames(projectcss.all, sty.svg__g93MW)}
          role={"img"}
        />
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  button: ["button", "iconFrame", "label"],
  iconFrame: ["iconFrame"],
  label: ["label"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  button: "div";
  iconFrame: "div";
  label: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBuildWithUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBuildWithUs__VariantsArgs;
    args?: PlasmicBuildWithUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBuildWithUs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBuildWithUs__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBuildWithUs__ArgProps,
          internalVariantPropNames: PlasmicBuildWithUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBuildWithUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "button") {
    func.displayName = "PlasmicBuildWithUs";
  } else {
    func.displayName = `PlasmicBuildWithUs.${nodeName}`;
  }
  return func;
}

export const PlasmicBuildWithUs = Object.assign(
  // Top-level PlasmicBuildWithUs renders the root element
  makeNodeComponent("button"),
  {
    // Helper components rendering sub-elements
    iconFrame: makeNodeComponent("iconFrame"),
    label: makeNodeComponent("label"),

    // Metadata about props expected for PlasmicBuildWithUs
    internalVariantProps: PlasmicBuildWithUs__VariantProps,
    internalArgProps: PlasmicBuildWithUs__ArgProps
  }
);

export default PlasmicBuildWithUs;
/* prettier-ignore-end */
